import { ChessPieceType, ChessPieceVariant } from "../chessPieceTypes";

const pieces = [
  {
    id: "black-rook-1",
    type: ChessPieceType.rook,
    name: "Black Rook 1",
    currZoneId: "0-0",
    owner: "1",
    variant: ChessPieceVariant.black,
  },
  {
    id: "black-knight-1",
    type: ChessPieceType.knight,
    name: "Black Knight 1",
    currZoneId: "1-0",
    owner: "1",
    variant: ChessPieceVariant.black,
  },
  {
    id: "black-bishop-1",
    type: ChessPieceType.bishop,
    name: "Black Bishop 1",
    currZoneId: "2-0",
    owner: "1",
    variant: ChessPieceVariant.black,
  },
  {
    id: "black-queen",
    type: ChessPieceType.queen,
    name: "Black Queen",
    currZoneId: "3-0",
    owner: "1",
    variant: ChessPieceVariant.black,
  },
  {
    id: "black-king",
    type: ChessPieceType.king,
    name: "Black King",
    currZoneId: "4-0",
    owner: "1",
    variant: ChessPieceVariant.black,
  },
  {
    id: "black-bishop-2",
    type: ChessPieceType.bishop,
    name: "Black Bishop 2",
    currZoneId: "5-0",
    owner: "1",
    variant: ChessPieceVariant.black,
  },
  {
    id: "black-knight-2",
    type: ChessPieceType.knight,
    name: "Black Knight 2",
    currZoneId: "6-0",
    owner: "1",
    variant: ChessPieceVariant.black,
  },
  {
    id: "black-rook-2",
    type: ChessPieceType.rook,
    name: "Black Rook 2",
    currZoneId: "7-0",
    owner: "1",
    variant: ChessPieceVariant.black,
  },
  {
    id: "black-pawn-1",
    type: ChessPieceType.pawn,
    name: "Black Pawn 1",
    currZoneId: "0-1",
    owner: "1",
    variant: ChessPieceVariant.black,
  },
  {
    id: "black-pawn-2",
    type: ChessPieceType.pawn,
    name: "Black Pawn 2",
    currZoneId: "1-1",
    owner: "1",
    variant: ChessPieceVariant.black,
  },
  {
    id: "black-pawn-3",
    type: ChessPieceType.pawn,
    name: "Black Pawn 3",
    currZoneId: "2-1",
    owner: "1",
    variant: ChessPieceVariant.black,
  },
  {
    id: "black-pawn-4",
    type: ChessPieceType.pawn,
    name: "Black Pawn 4",
    currZoneId: "3-1",
    owner: "1",
    variant: ChessPieceVariant.black,
  },
  {
    id: "black-pawn-5",
    type: ChessPieceType.pawn,
    name: "Black Pawn 5",
    currZoneId: "4-1",
    owner: "1",
    variant: ChessPieceVariant.black,
  },
  {
    id: "black-pawn-6",
    type: ChessPieceType.pawn,
    name: "Black Pawn 6",
    currZoneId: "5-1",
    owner: "1",
    variant: ChessPieceVariant.black,
  },
  {
    id: "black-pawn-7",
    type: ChessPieceType.pawn,
    name: "Black Pawn 7",
    currZoneId: "6-1",
    owner: "1",
    variant: ChessPieceVariant.black,
  },
  {
    id: "black-pawn-8",
    type: ChessPieceType.pawn,
    name: "Black Pawn 8",
    currZoneId: "7-1",
    owner: "1",
    variant: ChessPieceVariant.black,
  },
  {
    id: "white-rook-1",
    type: ChessPieceType.rook,
    name: "White Rook 1",
    currZoneId: "0-7",
    owner: "0",
    variant: ChessPieceVariant.white,
  },
  {
    id: "white-knight-1",
    type: ChessPieceType.knight,
    name: "White Knight 1",
    currZoneId: "1-7",
    owner: "0",
    variant: ChessPieceVariant.white,
  },
  {
    id: "white-bishop-1",
    type: ChessPieceType.bishop,
    name: "White Bishop 1",
    currZoneId: "2-7",
    owner: "0",
    variant: ChessPieceVariant.white,
  },
  {
    id: "white-queen",
    type: ChessPieceType.queen,
    name: "White Queen",
    currZoneId: "3-7",
    owner: "0",
    variant: ChessPieceVariant.white,
  },
  {
    id: "white-king",
    type: ChessPieceType.king,
    name: "White King",
    currZoneId: "4-7",
    owner: "0",
    variant: ChessPieceVariant.white,
  },
  {
    id: "white-bishop-2",
    type: ChessPieceType.bishop,
    name: "White Bishop 2",
    currZoneId: "5-7",
    owner: "0",
    variant: ChessPieceVariant.white,
  },
  {
    id: "white-knight-2",
    type: ChessPieceType.knight,
    name: "White Knight 2",
    currZoneId: "6-7",
    owner: "0",
    variant: ChessPieceVariant.white,
  },
  {
    id: "white-rook-2",
    type: ChessPieceType.rook,
    name: "White Rook 2",
    currZoneId: "7-7",
    owner: "0",
    variant: ChessPieceVariant.white,
  },
  {
    id: "white-pawn-1",
    type: ChessPieceType.pawn,
    name: "White Pawn 1",
    currZoneId: "0-6",
    owner: "0",
    variant: ChessPieceVariant.white,
  },
  {
    id: "white-pawn-2",
    type: ChessPieceType.pawn,
    name: "White Pawn 2",
    currZoneId: "1-6",
    owner: "0",
    variant: ChessPieceVariant.white,
  },
  {
    id: "white-pawn-3",
    type: ChessPieceType.pawn,
    name: "White Pawn 3",
    currZoneId: "2-6",
    owner: "0",
    variant: ChessPieceVariant.white,
  },
  {
    id: "white-pawn-4",
    type: ChessPieceType.pawn,
    name: "White Pawn 4",
    currZoneId: "3-6",
    owner: "0",
    variant: ChessPieceVariant.white,
  },
  {
    id: "white-pawn-5",
    type: ChessPieceType.pawn,
    name: "White Pawn 5",
    currZoneId: "4-6",
    owner: "0",
    variant: ChessPieceVariant.white,
  },
  {
    id: "white-pawn-6",
    type: ChessPieceType.pawn,
    name: "White Pawn 6",
    currZoneId: "5-6",
    owner: "0",
    variant: ChessPieceVariant.white,
  },
  {
    id: "white-pawn-7",
    type: ChessPieceType.pawn,
    name: "White Pawn 7",
    currZoneId: "6-6",
    owner: "0",
    variant: ChessPieceVariant.white,
  },
  {
    id: "white-pawn-8",
    type: ChessPieceType.pawn,
    name: "White Pawn 8",
    currZoneId: "7-6",
    owner: "0",
    variant: ChessPieceVariant.white,
  },
];

export default pieces;
